name: import-solution-to-target

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to import'
        required: true
      solution_input_file:
        description: 'Path to the solution zip file'
        default: 'out/exported'
      solution_folder:
        description: 'Folder where the solution is unpacked'
        default: 'out/solutions'

env:
  TARGET_ENVIRONMENT_URL: ${{ secrets.TARGET_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  GITTOKEN: ${{ secrets.GITTOKEN }}

jobs:
  import-to-target:
    runs-on: windows-latest
    timeout-minutes: 720

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Ensure folders exist
        run: |
          mkdir -p "${{ github.event.inputs.solution_input_file }}"
          mkdir -p "${{ github.event.inputs.solution_folder }}"
        shell: pwsh

      - name: Debug Vars
        run: |
          echo "TARGET_ENVIRONMENT_URL=$env:TARGET_ENVIRONMENT_URL"
          echo "CLIENT_ID=$env:CLIENT_ID"
          echo "TENANT_ID=$env:TENANT_ID"
          echo "CLIENT_SECRET length=$($env:CLIENT_SECRET.Length)"
          echo "GITTOKEN length=$($env:GITTOKEN.Length)"
        shell: pwsh

      - name: who-am-i
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}

      - name: pack-solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
          solution-file: ${{ github.event.inputs.solution_input_file }}/${{ github.event.inputs.solution_name }}.zip
          solution-type: 'Unmanaged'

      - name: import-solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          solution-input-file: ${{ github.event.inputs.solution_input_file }}/${{ github.event.inputs.solution_name }}.zip
