name: deploy-solution-to-test

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to deploy'
        required: true
      source_branch:
        description: 'Git branch to pick the solution from'
        default: main

env:
  TARGET_ENVIRONMENT_URL: ${{ secrets.TARGET_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  GITTOKEN: ${{ secrets.GITTOKEN }}

jobs:
  deploy-to-test:
    runs-on: windows-latest
    timeout-minutes: 720

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.source_branch }}
          lfs: true

      - name: Debug Vars
        run: |
          echo "TARGET_ENVIRONMENT_URL=$env:TARGET_ENVIRONMENT_URL"
          echo "CLIENT_ID=$env:CLIENT_ID"
          echo "TENANT_ID=$env:TENANT_ID"
          echo "CLIENT_SECRET length=$($env:CLIENT_SECRET.Length)"
          echo "GITTOKEN length=$($env:GITTOKEN.Length)"
        shell: pwsh

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Who Am I (Test Environment)
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}

      - name: Import Managed Solution to Test
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          solution-file: ./out/exported/${{ github.event.inputs.solution_name }}_Managed.zip
          activate-plugins: true
          force-overwrite: false
          skip-dependency-check: false
          convert-to-managed: true

      - name: Publish Solution in Test
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
