name: deploy-solution-to-test
# Deploy a solution from Git to a Test environment as Managed

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to deploy'
        required: true
        default: Zyris
      source_branch:
        description: 'Git branch to pick the solution from'
        required: true
        default: main

env:
  TARGET_ENVIRONMENT_URL: ${{ secrets.TARGET_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

permissions:
  contents: write
  id-token: write

jobs:
  deploy-to-test:
    runs-on: windows-latest
    timeout-minutes: 720
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Checkout selected branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.source_branch }}
        lfs: true

    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Who Am I (Test Environment)
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Pack Solution (Managed)
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ./solutions/${{ github.event.inputs.solution_name }}
        zip-file: ./out/managed/${{ github.event.inputs.solution_name }}.zip
        solution-type: Managed
        overwrite: true

    - name: Import Managed Solution
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-file: ./out/managed/${{ github.event.inputs.solution_name }}.zip
        overwrite-unmanaged-customizations: false
        publish-workflows: true
        solution-type: Managed

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
