name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to export'
        required: true
      solution_exported_folder:
        description: 'Folder to store the exported solution zip'
        default: 'out/exported'
      solution_folder:
        description: 'Folder to unpack the solution'
        default: 'out/solutions'
      solution_target_folder:
        description: 'Folder to commit solution into'
        default: 'solutions'

env:
  ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  GITTOKEN: ${{ secrets.GITTOKEN }}

jobs:
  export-from-dev:
    runs-on: windows-latest
    timeout-minutes: 720

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Ensure folders exist
        run: |
          mkdir -p "${{ github.event.inputs.solution_exported_folder }}"
          mkdir -p "${{ github.event.inputs.solution_folder }}"
          mkdir -p "${{ github.event.inputs.solution_target_folder }}"
        shell: pwsh

      - name: Debug Vars
        run: |
          echo "ENVIRONMENT_URL=$env:ENVIRONMENT_URL"
          echo "CLIENT_ID=$env:CLIENT_ID"
          echo "TENANT_ID=$env:TENANT_ID"
          echo "CLIENT_SECRET length=$($env:CLIENT_SECRET.Length)"
          echo "GITTOKEN length=$($env:GITTOKEN.Length)"
        shell: pwsh

      - name: who-am-i
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}

      - name: export-solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip

      - name: unpack-solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: branch-solution
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ github.event.inputs.solution_target_folder }}/${{ github.event.inputs.solution_name }}
          repo-token: ${{ env.GITTOKEN }}
          allow-empty-commit: true
