name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to export'
        required: true
        default: Zyris

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Solution name is ${{ github.event.inputs.solution_name }}"
