name: export-and-branch-solution
# Export solution from DEV environment (PT),
# unpack it, commit to Git, and also export Managed zip for deployment

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: Zyris
      solution_exported_folder:
        description: 'Folder name for staging the exported solution (do not change)'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Staging folder for unpacked solution before check-in (do not change)'
        required: true
        default: out/solutions/
      solution_target_folder: 
        description: 'Folder name to be created and checked in (do not change)'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    timeout-minutes: 720
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Who Am I
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Export Unmanaged Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip
        managed: false

    - name: Export Managed Solution (for Test env)
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ./out/managed/${{ github.event.inputs.solution_name }}.zip
        managed: true

    - name: Unpack Unmanaged Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
        solution-type: Unmanaged
        overwrite-files: true

    - name: Publish Unmanaged Solution in PT
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Branch Solution (prepare for PR)
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder }}${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
