name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: Zyris

env:
  ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}

permissions:
  id-token: write      # 🔑 REQUIRED for OIDC authentication
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    timeout-minutes: 720
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Who Am I
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        tenant-id: ${{ env.TENANT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        tenant-id: ${{ env.TENANT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: out/${{ github.event.inputs.solution_name }}.zip

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: out/${{ github.event.inputs.solution_name }}.zip
        solution-folder: out/solutions/${{ github.event.inputs.solution_name }}
        solution-type: Unmanaged
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        tenant-id: ${{ env.TENANT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}

    - name: Branch Solution (prepare for PR)
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/${{ github.event.inputs.solution_name }}
        solution-target-folder: src/solutions/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
